
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci-cd"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "gomod"
    directory: "/build"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "maven"
    directory: "/build"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/build"
    schedule:
      interval: "daily"
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/build/python"
    schedule:
      interval: "daily"
    target-branch: "develop"
