version: '3.8'

services:
  flask:
    build: ./app
    ports:
      - "5000:5000"

  vault:
    image: hashicorp/vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"

  istio:
    image: istio/proxyv2
    ports:
      - "15021:15021"
