apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-app
spec:
  hosts:
    - flask-app.example.com
  gateways:
    - flask-app-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: flask-app
            port:
              number: 5000
